"""Add pending_orders table

Revision ID: 02b0a1512c65
Revises: 009a738b8fc6
Create Date: 2025-04-18 16:15:45.315932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02b0a1512c65'
down_revision: Union[str, None] = '009a738b8fc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('order_type', sa.Enum('MARKET_BUY', 'MARKET_SELL', 'LIMIT_BUY', 'LIMIT_SELL', name='ordertype'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'EXECUTED', 'CANCELLED', 'EXPIRED', name='orderstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_pending_order_quantity_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_orders_id'), 'pending_orders', ['id'], unique=False)
    op.create_index(op.f('ix_pending_orders_status'), 'pending_orders', ['status'], unique=False)
    op.create_index(op.f('ix_pending_orders_symbol'), 'pending_orders', ['symbol'], unique=False)
    op.create_index(op.f('ix_pending_orders_user_id'), 'pending_orders', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_orders_user_id'), table_name='pending_orders')
    op.drop_index(op.f('ix_pending_orders_symbol'), table_name='pending_orders')
    op.drop_index(op.f('ix_pending_orders_status'), table_name='pending_orders')
    op.drop_index(op.f('ix_pending_orders_id'), table_name='pending_orders')
    op.drop_table('pending_orders')
    # ### end Alembic commands ###
